# Generated by Django 3.0.6 on 2020-05-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default='Headline', max_length=128),
            preserve_default=False,
        ),
    ]
