# Generated by Django 3.0.6 on 2020-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200505_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(null=True, related_name='posts', to='stories.Author'),
        ),
    ]
